// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetLatestTransactions():Promise<Array<models.LatestTransaction>>;

export function GetLeaderboard():Promise<Array<models.TransactionLeaderboard>>;

export function ScanUpc(arg1:string):Promise<any>;

export function Strecka(arg1:number,arg2:string,arg3:number):Promise<any>;
