// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestTransactions() {
  return window['go']['desktop']['App']['GetLatestTransactions']();
}

export function GetLeaderboard() {
  return window['go']['desktop']['App']['GetLeaderboard']();
}

export function ScanUpc(arg1) {
  return window['go']['desktop']['App']['ScanUpc'](arg1);
}

export function Strecka(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['Strecka'](arg1, arg2, arg3);
}
