// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * You can keep your existing Close method if needed
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Close() {
    let $resultPromise = /** @type {any} */($Call.ByID(2589043263));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Connect() {
    let $resultPromise = /** @type {any} */($Call.ByID(2663552037));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Name() {
    let $resultPromise = /** @type {any} */($Call.ByID(1140382954));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OnShutdown() {
    let $resultPromise = /** @type {any} */($Call.ByID(402631574));
    return $resultPromise;
}

/**
 * @param {any} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OnStartup(options) {
    let $resultPromise = /** @type {any} */($Call.ByID(1740741053, options));
    return $resultPromise;
}
