// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../models/models.js";

/**
 * @returns {Promise<models$0.LatestTransaction[]> & { cancel(): void }}
 */
export function GetLatestTransactions() {
    let $resultPromise = /** @type {any} */($Call.ByID(1198783294));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<models$0.TransactionLeaderboard[]> & { cancel(): void }}
 */
export function GetLeaderboard() {
    let $resultPromise = /** @type {any} */($Call.ByID(872526387));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} upc
 * @returns {Promise<any> & { cancel(): void }}
 */
export function ScanUpc(upc) {
    let $resultPromise = /** @type {any} */($Call.ByID(862128925, upc));
    return $resultPromise;
}

/**
 * @param {number} ProductID
 * @param {string} UserID
 * @param {number} amount
 * @returns {Promise<any> & { cancel(): void }}
 */
export function Strecka(ProductID, UserID, amount) {
    let $resultPromise = /** @type {any} */($Call.ByID(3455500751, ProductID, UserID, amount));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.LatestTransaction.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.TransactionLeaderboard.createFrom;
const $$createType3 = $Create.Array($$createType2);
