// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Service wraps a bound type instance.
 * The zero value of Service is invalid.
 * Valid values may only be obtained by calling [NewService].
 */
export class Service {
    /**
     * Creates a new Service instance.
     * @param {Partial<Service>} [$$source = {}] - The source object to create the Service.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Service}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service(/** @type {Partial<Service>} */($$parsedSource));
    }
}
